### ISSUE TITLE
Returning whitespace instead of 0

### ISSUE THREAD

**Issue by lachlanbell** [idrougge/sha1-swift#1]
Hi,
Thanks for writing this!
Just one small issue: I've noticed that when a `0` is at the start of a hex block in a returned hash, it is replaced with a whitespace, e.g:

`1234567890` returns ` 1B307AC BA4F54F5 5AAFC33B B06BBBF6 CA803E9A` instead of `01B307AC BA4F54F5 5AAFC33B B06BBBF6 CA803E9A`, `password` returns `5BAA61E4 C9B93F3F  682250B 6CF8331B 7EE68FD8` instead of `5BAA61E4 C9B93F3F 0682250B 6CF8331B 7EE68FD8`

Cheers

**Comment by idrougge** [comment]
Thank you for your report! This problem should be fixed in `master` now.
